const proveedoresArray = [
  {
    nombre_empresa: "Farmacia Labs",
    contacto_nombre: "Gerente de Compras",
    contacto_telefono: "123-456-7890",
    direccion: "Calle Principal #123",
    email: "compras@farmacialabs.com",
  },
  {
    nombre_empresa: "Salud Pharma",
    contacto_nombre: "Director de Compras",
    contacto_telefono: "987-654-3210",
    direccion: "Avenida Central #456",
    email: "compras@saludpharma.com",
  },
  {
    nombre_empresa: "Digest Pharma",
    contacto_nombre: "Coordinador de Compras",
    contacto_telefono: "555-7890",
    direccion: "Plaza Comercial #789",
    email: "compras@digestpharma.com",
  },
  {
    nombre_empresa: "Wellness Pharmaceuticals",
    contacto_nombre: "Responsable de Compras",
    contacto_telefono: "111-222-3333",
    direccion: "Avenida Saludable #111",
    email: "compras@wellnesspharma.com",
  },
  {
    nombre_empresa: "Global Pharmaceuticals",
    contacto_nombre: "Jefe de Compras Internacionales",
    contacto_telefono: "555-1234",
    direccion: "Calle Global #555",
    email: "compras@globalpharma.com",
  },
  {
    nombre_empresa: "Health Supplements Co.",
    contacto_nombre: "Encargado de Adquisiciones",
    contacto_telefono: "777-888-9999",
    direccion: "Calle de los Suplementos #777",
    email: "adquisiciones@healthsupplementsco.com",
  },
  {
    nombre_empresa: "Allergen Pharmaceuticals",
    contacto_nombre: "Coordinador de Compras",
    contacto_telefono: "333-444-5555",
    direccion: "Avenida Antialérgica #333",
    email: "compras@allergenpharma.com",
  },
  {
    nombre_empresa: "Cardio Health Labs",
    contacto_nombre: "Especialista en Adquisiciones",
    contacto_telefono: "666-777-8888",
    direccion: "Calle Cardíaca #666",
    email: "adquisiciones@cardiohealthlabs.com",
  },
  {
    nombre_empresa: "Hydration Solutions Inc.",
    contacto_nombre: "Director de Compras",
    contacto_telefono: "999-000-1111",
    direccion: "Calle de la Hidratación #999",
    email: "compras@hydrationinc.com",
  },
];
