const recetasArray = [
  {
    paciente_nombre: "Juan Pérez",
    medico_nombre: "Dr. García",
    fecha_emision: "2023-03-05",
    fecha_expiracion: "2023-04-05",
    estado: "activa",
    observaciones: "Tomar una tableta cada 12 horas.",
  },
  {
    paciente_nombre: "María Gómez",
    medico_nombre: "Dra. Martínez",
    fecha_emision: "2023-03-08",
    fecha_expiracion: "2023-04-08",
    estado: "expirada",
    observaciones: "Suspender si hay efectos secundarios.",
  },
  {
    paciente_nombre: "Pedro Rodríguez",
    medico_nombre: "Dr. López",
    fecha_emision: "2023-03-10",
    fecha_expiracion: "2023-04-10",
    estado: "activa",
    observaciones: "Tomar con alimentos.",
  },
  {
    paciente_nombre: "Ana Martínez",
    medico_nombre: "Dra. Pérez",
    fecha_emision: "2023-03-12",
    fecha_expiracion: "2023-04-12",
    estado: "expirada",
    observaciones: "Consultar al médico si hay cambios.",
  },
  {
    paciente_nombre: "Carlos González",
    medico_nombre: "Dr. Sánchez",
    fecha_emision: "2023-03-15",
    fecha_expiracion: "2023-04-15",
    estado: "activa",
    observaciones: "Evitar el consumo de alcohol.",
  },
  {
    paciente_nombre: "Luisa Fernández",
    medico_nombre: "Dra. Romero",
    fecha_emision: "2023-03-18",
    fecha_expiracion: "2023-04-18",
    estado: "expirada",
    observaciones: "Revisar presión arterial regularmente.",
  },
  {
    paciente_nombre: "Elena Santos",
    medico_nombre: "Dr. Díaz",
    fecha_emision: "2023-03-20",
    fecha_expiracion: "2023-04-20",
    estado: "activa",
    observaciones: "No suspender el tratamiento abruptamente.",
  },
  {
    paciente_nombre: "Miguel López",
    medico_nombre: "Dra. Ruiz",
    fecha_emision: "2023-03-23",
    fecha_expiracion: "2023-04-23",
    estado: "expirada",
    observaciones: "Almacenar en un lugar fresco y seco.",
  },
  {
    paciente_nombre: "Isabel Ramírez",
    medico_nombre: "Dr. González",
    fecha_emision: "2023-03-25",
    fecha_expiracion: "2023-04-25",
    estado: "activa",
    observaciones: "Tomar con un vaso de agua.",
  },
];
